package treeapp.search;

public enum SearchType {
    BFS,
    BFS_ONLY_LEAFS,
    DFS_ONLY_LEAFS_RECURSIVE,
    DFS_ONLY_LEAFS_ITERATIVE,
    DFS_PREORDER_RECURSIVE,
    DFS_PREORDER_ITERATIVE,
    DFS_INORDER_RECURSIVE,
    DFS_INORDER_ITERATIVE,
    DFS_POSTORDER_RECURSIVE,
    DFS_POSTORDER_ITERATIVE
}
